# Spring configuration
spring:
  # application properties
  application:
    name: TruckProject2

  # datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/truck_db2?serverTimezone=UTC
    username: root
    password: 1999Sergey

  # JPA and Hibernate properties
  jpa:
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: true

  # MVC configuration properties
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Resources configuration
  resources:
    static-locations: /resources/

  # Messages resource config
  messages:
    basename: messages