# Spring configuration
spring:
  # application properties
  application:
    name: TruckProject2

  # datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/truck_db3?serverTimezone=UTC
    username: root
    password: 1999Sergey

  # JPA and Hibernate properties
  jpa:
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: true

  # Messages resource config
  messages:
    basename: messages